### ISSUE TITLE
confused about the credentials

### ISSUE THREAD

**Issue by hyusetiawan** [lionheart/bottlenose#71]
the credentials are confusing me, so there is AWS but there is also MWS, my intention is to get things like the Best Sellers Rank of an ASIN, can I use bottlenose for that? 

All I have is MWS account, I can register for the AWS credential from amazon associate but there is a limitation of "You must drive at least three qualified sales within 180 days in order to avoid termination of your Associate account." for amazon associates program (where I can get the API)

Is it possible to use bottlenose for MWS related activities such as GetMatchingProductForId? I tried to no avail but it could be im passing incorrect credentials (using MWS) to bottlenose

**Comment by dlo** [comment]
Yep, that's exactly what bottlenose is for.

Since this isn't a bug with bottlenose could you please ask this on StackOverflow and post the question URL in a follow-up comment? There is a "bottlenose" tag that you can use to categorize the question. See https://github.com/lionheart/bottlenose#communication for more information. Thanks! 👍

**Comment by hyusetiawan** [comment]
@dlo thank you for the response :)
here is the URL: https://stackoverflow.com/questions/50536129/bottlenose-with-mws
I am still confused on what to provide, if you could please help, that'd be appreciated
